image: Visual Studio 2019
platform: x64
environment:
  nodejs_version: "16"
  PYTHON: C:\Python27\python.exe
install:
  - ps: Install-Product node $env:nodejs_version
  - choco install python2
  - choco install yarn
  - yarn install
build_script:
  - yarn build
  - yarn dist:win
artifacts:
  - path: dist\*.exe
    name: HaikuAnimatorWindows
